### ISSUE TITLE
todo: todoリスト

### ISSUE THREAD

**Issue by laminne** [mct-joken/kojs5-backend#37]
- [ ] feat(submission): KnockOutを実装する
- [ ] #42
- [ ] feat(problem): 得点の自動計算
- [ ] feat(problem): 通し番号"A - <title>"を定義する
- [ ] refactor(submission/queue): Queueを消す
- [ ] #40
- [ ] #41
